name: CI 🏗

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_test:
    name: Lint & test code.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
      - name: Lint Go code
        uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.55.2"
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -race -cover ./...
